package main.enums;

public enum Menu {
    PRINT_ALL_TASK,
    DELETE_ALL_TASK,
    GET_ID_TASK,
    CREATE_TASK,
    UPDATE_TASK,
    DELETE_TASK_ID,
    PRINT_ALL_EPIC,
    DELETE_ALL_EPIC,
    GET_ID_EPICS,
    CREATE_EPIC,
    UPDATE_EPIC,
    DELETE_EPIC_ID,
    PRINT_ALL_SUBTASKS,
    DELETE_ALL_SUBTASKS,
    GET_ID_SUBTASK,
    CREATE_SUBTASK,
    UPDATE_SUBTASK,
    DELETE_SUBTASK,
    PRINT_ALL_SUBTASKS_EPIC,
    EXIT
}
